### ISSUE TITLE
ConfirmBox.confirm只传4个参数onCancel会报错

### ISSUE THREAD

**Issue by xuxin** [aralejs/dialog#57]
只传4个参数onCancel形参会被置为option对象，导致onCancel时如下语句执行报错
onCancel && onCancel();

**Comment by afc163** [comment]
看代码的话应该已经不存在这个问题了。

https://github.com/aralejs/dialog/blob/1360fbee9e412b7bd73d279283549e88f7f83061/src/confirmbox.js#L82
