### ISSUE TITLE
增加跨域iframe支持

### ISSUE THREAD

**Issue by shaoshuai0102** [aralejs/dialog#90]
使用arale-messenger进行跨域通信。无需设置document.domain，防止xss扩散。

缺点是iframe内部实现需要接入messenger。

**Comment by shaoshuai0102** [comment]
iframe页面接入这个组件 https://github.com/aralejs/dialog-iframe-helper

**Comment by afc163** [comment]
赞赞赞

**Comment by shaoshuai0102** [comment]
现在arale的版本升级怎么操作的，PR谁来合并，版本谁来发布？
