### ISSUE TITLE
contentWindow在IE678中报未指明的错误

### ISSUE THREAD

**Issue by Rockcookies** [aralejs/dialog#94]
使用messager进行跨域绑定时，m.addTarget(this.iframe[0].contentWindow, 'iframe1');这行代码报错。

在IE6-8中Iframe创建后马上访问iframe的contentWindow对象会报“未指明的错误”，经测试，可以在iframe的load事件中可以访问contentWindow对象。

**Comment by afc163** [comment]
欢迎 PR。
为啥提到 dialog 里？

**Comment by Rockcookies** [comment]
可否将messager绑定contentWindow移动至load事件中？
