### ISSUE TITLE
http://static.alipayobjects.com 托管的最新arale组件地址

### ISSUE THREAD

**Issue by dennyding** [aralejs/dialog#96]
你好
aralejs.org官网上的5分钟快速上手处，那个实例程序（飞动的小球）在本地失效，初步判断是CDN托管的问题，试了下部分其他组件也有这个问题，想问下哪里有最新的各组件托管地址？

自己在本地构建总是各种错误，所以想直接用阿里的CDN，谢谢~

**Comment by afc163** [comment]
具体是什么方式运行失效？http://jsfiddle.net/zPYqx/85/ 这个演示是可以跑的。

**Comment by dennyding** [comment]
我也建了一个实例：http://runjs.cn/code/siovy4jh 请帮我看一下是啥问题。
我直接把那个代码复制到本地，也是一样的问题。

另外，你们那些组件的alias路径都是有一定规律的吧？比如日历是不是，'calendar':'calendar/1.1.2/index' 
，我根据首页那个版本号推断的

**Comment by afc163** [comment]
原来的例子代码有问题，alias 写错了。现在已经改过来了，你再试试。

路径是有规律的，每部分的含义在这里讲得很清楚：http://127.0.0.1:8000/docs/getting-started.html

**Comment by afc163** [comment]
另外，推荐使用 standalone 的方式进行开发，无须依赖复杂的 loader 配置和 cdn 地址。http://aralejs.org/docs/develop-components.html#script-引用

简单的入门可以看看：https://github.com/spmjs/docs/blob/master/package/get-started.md

**Comment by dennyding** [comment]
好的，马上试试。多谢指点~
这些组件支持移动端吗？是不是可以直接用zepto替代jQuery（貌似在某个地方看到玉伯说过这个观点）
最近搞了移动端轻应用微创业项目，需要用到这些组件

**Comment by dennyding** [comment]
standalone这个很好，但我想到一个问题：如果我两个不同模块（a,b)依赖同一个模块(c)，如果这两个模块都用 standalone build 出a.js和b.js, 那这两文件里头是不是都有c的代码内容，这样不是重复加载吗？

**Comment by dennyding** [comment]
http://aralejs.org/docs/getting-started.html#%E4%BD%BF%E7%94%A8-seajs 这个地方关于模块alias的描述，我始终是一团浆糊。

1. 前后矛盾
    说position的路径是http://static.alipayobjects.com/position/1.1.0/position.js，就和小球那个例子矛盾，里头写的是'position': 'position/1.1.0/index'

2. 其他组件走不通
    calendar搞了半天也搞不出来， 'calendar': 'calendar/1.1.2/calendar' 和 'calendar': 'calendar/1.1.2/index'
都试了，就是不行，莫名其妙

建议直接把各组件的alias全部写出来，再搞个小球那样的实例，否则这文档真的很折腾人啊。

**Comment by afc163** [comment]
1. 是 `position/1.1.0/index`，文档有误。
2. 依然不建议用 loader 。

**Comment by dennyding** [comment]
为什么不建议用loader？能说说原因吗？

**Comment by dennyding** [comment]
另外spm 3.6.0里面 spm build --standalone这个命令也没有了，请看截图。
还有别的方法能这样build吗？
我真的很想用这些组件，但是折腾了三天，还是搞不定
![qq 20150509123806](https://cloud.githubusercontent.com/assets/1400115/7548715/b54f013e-f648-11e4-981d-7c419bcbb6a8.png)

**Comment by afc163** [comment]
loader 需要把当前模块依赖路径上的所有模块都提前发到线上，才可以使用。这点非常反人类。

spm@3.6 之后，`spm build` 默认就是 standalone 的打包方式。文档可以参考：https://github.com/spmjs/docs

目前的文档比较混乱，还待官方整理。

**Comment by dennyding** [comment]
按照这篇教程 https://github.com/spmjs/docs/blob/master/project/get-started.md  总算把组件引入自己的项目了，不过使用方法跟arale官方论坛大不一样，感觉官网有点误导人的意思了。
我问题已经解决了，close issule

**Comment by afc163** [comment]
因为 Arale 做的比较早，偏向于 Sea.js 的方案。现在我们都推荐 standalone 的方式来使用模块。

而且 Arale 和 spm 本身并没有什么联系。

**Comment by dennyding** [comment]
afc大哥，我现在想实现：模块任何一个js文件修改后，就自动spm build standalone一遍到指定的位置，这个怎么弄啊？
原因是HTML是PHP生成的，用那个8000的端口调试不方便，因为那个数据是死的

在gulp里面能实现吗？感觉可以，但找不到方法，请指点一下。谢谢

**Comment by dennyding** [comment]
afc大哥，我现在想实现：模块任何一个js文件修改后，就自动spm build standalone一遍到指定的位置，这个怎么弄啊？
原因是HTML是PHP生成的，用那个8000的端口调试不方便，因为那个数据是死的

在gulp里面能实现吗？感觉可以，但找不到方法，请指点一下。谢谢
